openapi: 3.1.0
x-stoplight:
  id: l59olb2m3xd44
info:
  title: HM-Api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /patients:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
                  x-stoplight:
                    id: e8jvnfpml8wz8
      operationId: get-patients
  /doctors:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Doctor'
                  x-stoplight:
                    id: ytnngrx1x4uc0
      operationId: get-doctors
  '/patient/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
      operationId: get-patient-id
components:
  schemas:
    Patient:
      title: Patient
      x-stoplight:
        id: ehj0rxmllxl53
      type: object
      x-internal: true
      additionalProperties: false
      properties:
        id:
          type: integer
        firstName:
          type: string
          x-stoplight:
            id: lj51chfgni4oy
        lastName:
          type: string
          x-stoplight:
            id: sy8gdh0a7b75c
        birthDate:
          type: string
          x-stoplight:
            id: 4fkqayk1rxw0k
          format: date
        email:
          type: string
          x-stoplight:
            id: c7m1hxcm18jpm
        phoneNumber:
          type: string
          x-stoplight:
            id: tut04dyumv5x2
      required:
        - id
        - lastName
    Doctor:
      title: Doctor
      x-stoplight:
        id: es3g4xxdpedy4
      type: object
      x-internal: true
      additionalProperties: false
      properties:
        id:
          type: integer
        firstName:
          type: string
          x-stoplight:
            id: 1nkfwfcmql8wv
        lastName:
          type: string
          x-stoplight:
            id: cw2zry1s3cewb
        email:
          type: string
          x-stoplight:
            id: feqf44od7o0cg
        phoneNumber:
          type: string
          x-stoplight:
            id: srxcsct3os5dy
      required:
        - id
        - lastName
